<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <AssemblyName>TechSupportReply.Indexer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TechSupportReply.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TechSupportReply.Core\TechSupportReply.Core.csproj" />
    <ProjectReference Include="..\TechSupportReply.Rag\TechSupportReply.Rag.csproj" />
  </ItemGroup>
</Project>
