<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TechSupportReply.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TechSupportReply.Core\TechSupportReply.Core.csproj" />
  </ItemGroup>
</Project>
